name: Deploy
run-name: ${{ github.actor  }} is deploying the app 🚀

on:
  release:
    types: [published]

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN  }}
  ID_CLIENTE: ${{secrets.ID_CLIENTE }}
  LAT_ORIGEN: ${{secrets.LAT_ORIGEN }}
  LNG_ORIGEN: ${{secrets.LNG_ORIGEN }}
  IDS_JERARQUIA_TRAMITES: ${{secrets.IDS_JERARQUIA_TRAMITES }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: pip install -r requirements.txt
      - run: npm install -g serverless
      - run: sls plugin install -n serverless-python-requirements
      - run: sls plugin install -n serverless-lift
      - run: sls deploy
