name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - run: |
        pylint $(git ls-files '*.py') --fail-under=6